# Generated by Django 5.0 on 2024-09-14 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_owed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="amount",
            new_name="total_amount",
        ),
        migrations.AlterUniqueTogether(
            name="balance",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="expense",
            name="paid_by",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="participants",
        ),
        migrations.AddConstraint(
            model_name="balance",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_user_balance"
            ),
        ),
        migrations.AddField(
            model_name="expenseparticipant",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="core.expense",
            ),
        ),
        migrations.AddField(
            model_name="expenseparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
