# Generated by Django 5.0 on 2024-09-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_expenseparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
