# Generated by Django 5.0 on 2024-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_expense_is_active_expense_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("food", "Food"),
                    ("transport", "Transport"),
                    ("accommodation", "Accommodation"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="joining_code",
            field=models.CharField(default="", max_length=100),
        ),
    ]
