# Generated by Django 5.0 on 2024-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_crew_category_crew_joining_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crew",
            name="category",
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("food", "Food"),
                    ("transport", "Transport"),
                    ("accommodation", "Accommodation"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=100,
            ),
        ),
    ]
