# Generated by Django 5.0 on 2024-09-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userrole_basicroledemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
